
spring:
  application:
    name: BookingCreelHouse
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  # Step 1a: Configure SSL with the certificate and private key
  ssl:
    bundle:
      pem:
        web:
          keystore:
            privatekey: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2JPNE1ycm1EYnFObTZyM3YKV0paWWpqK3hKcVhvTE1qcmlJYVJYQmdISzRLaFJBTkNBQVR6TFZnbmdkYVJFMS9oN2lWdWRobTVKc3I5aUtrYQpTT3p2UWgyTSszQm5kQ2NaNzBZQ2ZOYXpzYU01Rng0SGRoZGpQT1E2Mzh5MWQ2VjE1WkdBc1F1bgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI3VENDQVpTZ0F3SUJBZ0lRRy9kVzhSbDJ3b1o2TTFNa1ZLS29vVEFLQmdncWhrak9QUVFEQWpCUE1SNHcKSEFZRFZRUUtFeFZ0YTJObGNuUWdaR1YyWld4dmNHMWxiblFnUTBFeEVqQVFCZ05WQkFzTUNXdGhiR2xBYTJGcwphVEVaTUJjR0ExVUVBd3dRYld0alpYSjBJR3RoYkdsQWEyRnNhVEFlRncweU5qQTBNVFV4TWpVd05UVmFGdzB5Ck9EQTNNVFV4TWpVd05UVmFNRDB4SnpBbEJnTlZCQW9USG0xclkyVnlkQ0JrWlhabGJHOXdiV1Z1ZENCalpYSjAKYVdacFkyRjBaVEVTTUJBR0ExVUVDd3dKYTJGc2FVQnJZV3hwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRTh5MVlKNEhXa1JOZjRlNGxiblladVNiSy9ZaXBHa2pzNzBJZGpQdHdaM1FuR2U5R0FueldzN0dqCk9SY2VCM1lYWXp6a090L010WGVsZGVXUmdMRUxwNk5rTUdJd0RnWURWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWQKSlFRTU1Bb0dDQ3NHQVFVRkJ3TUJNQjhHQTFVZEl3UVlNQmFBRlBsd1N2RURHZTdMVGFyMUZzS0F1NXZ1M3RwSwpNQm9HQTFVZEVRUVRNQkdDRDJ4dlkyRnNMakI0WkdKbExtUmxkakFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUJwCjdVSW5mZWQvL0pFQmw3Z2VtcG1jSlZORFBlT0hJUVJoQUZuTVBubU9RUUlnVjUwSGpkR05mSnI3a2xzeUZkMGcKY3dBSU0yQXJkNEdFZDJ3ZkpVWE9PdTQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
          trustore:
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI0akNDQVllZ0F3SUJBZ0lRUGtGWWs4MTI2UXA4bDIvZVZERGxSakFLQmdncWhrak9QUVFEQWpCUE1SNHcKSEFZRFZRUUtFeFZ0YTJObGNuUWdaR1YyWld4dmNHMWxiblFnUTBFeEVqQVFCZ05WQkFzTUNXdGhiR2xBYTJGcwphVEVaTUJjR0ExVUVBd3dRYld0alpYSjBJR3RoYkdsQWEyRnNhVEFlRncweU5qQTBNVFV4TWpRMU16SmFGdzB6Ck5qQTBNVFV4TWpRMU16SmFNRTh4SGpBY0JnTlZCQW9URlcxclkyVnlkQ0JrWlhabGJHOXdiV1Z1ZENCRFFURVMKTUJBR0ExVUVDd3dKYTJGc2FVQnJZV3hwTVJrd0Z3WURWUVFEREJCdGEyTmxjblFnYTJGc2FVQnJZV3hwTUZrdwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXNKS2RTT3NoTC9YemFzMVArTkxCMDhXY3IxSlplR2EwCnVVY21KaHY1NjEySys5T2hSd0I3S1NMV1dnTWQrckkxS3F4Z1BNVkdDc2RveVhuSENrUlZXS05GTUVNd0RnWUQKVlIwUEFRSC9CQVFEQWdJRU1CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGUGx3U3ZFRApHZTdMVGFyMUZzS0F1NXZ1M3RwS01Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRRG0rQnZhbVBPUzdQVFB0RVNSCkZCZzYvNm1uem91MmJIOUFHV3lHUEx6QkV3SWhBUEcrUVIxS2UvUGQ4TUUxUlBFSmRac1BGd0krZ1J6UEt3SkgKaXpsNnhqY3oKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  # Step 1a: End of SSL configuration

server:
  port: 8443
  # Step 1b: Enable SSL and specify ssl bundle
  # Step 1b: End of SSL configuration
  # Step 5: Configure session cookie with SameSite attribute
  # ...
  # Step 5: End of session cookie configuration
